studentapp/urls.py
from django.urls import path
from studentapp import views

# function based view

urlpatterns = [
    path('list/', views.list,name='list'),
    path('home/', views.home,name='home'),
    path('about/', views.about,name='about'),
    path('create/', views.create,name='create'),
    path('view/<int:id>', views.details,name='view'),
    path('edit/<int:id>', views.edit,name='edit'),
    path('delete/<int:id>', views.delete,name='delete'),
    
]

studentprj/urls.py
from django.contrib import admin
from django.urls import path,include
from studentapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('about/', views.about,name='about'),
    path('createnew/', views.create,name='create'),
    path('stud/', include('studentapp.urls')),
    path('utils/', include('utils.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/',views.register,name='register'),
]

utils/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('sendemail/', views.sent_mail,name='sendemail'),
    path('exportcsv/', views.export_csv,name='exportcsv'),
]

studentapp/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class Student(models.Model):
    GENDER_CHOICES = [('Male','Male'),('Female','Female'),('Other','Other'),]
    
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True,blank=True,null=True)
    dob = models.DateField(default=datetime.now,blank=True)
    gender = models.CharField(max_length=6,choices=GENDER_CHOICES,default='Male')
    
    def __str__(self) -> str:
        return f'{self.id} {self.name} {self.email} {self.dob} {self.gender}'
        

utils/models.py
from django.db import models

# Create your models here.

studentapp/forms.py
from django import forms
from .models import Student
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"
        
        labels = {'dob':'Date of Birth'}
        
class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(required=False,max_length=100)
    last_name = forms.CharField(required=False,max_length=100)
    
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1','password2',)
    
    

utils/forms.py
from django import forms

class EmailForm(forms.Form):
    email = forms.EmailField(max_length=100, widget=forms.TextInput())
    subject = forms.CharField(max_length=100, widget=forms.TextInput())
    message = forms.CharField(max_length=100, widget=forms.Textarea(),label=(''))
    attach = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple':True}))

studentapp/views.py
from django.shortcuts import redirect, render 
from studentapp.forms import StudentForm, SignUpForm
from studentapp.models import Student
from django.core.paginator import Paginator
from django.contrib import messages

from django.http import HttpResponse
from studentapp.models import Student
import csv

# Create your views here.

# function based view

def home(request):
    context = {'title':'Home'}
    return render(request,'stud/home.html',context)

def list(request):
    # students = Student.objects.all()
    std = Student.objects.order_by('-id')
    stdlist = std
    paginator = Paginator(stdlist,5)
    page = request.GET.get('page')
    std = paginator.get_page(page)
    
    context = {'title':'Student List','students': std}
    return render(request,'stud/list.html',context)

def about(request):
    context = {'title':'About Us'}
    return render(request,'stud/about.html',context)

def create(request):
    # POST = when submit 
    # GET = before submit 
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Data inserted successfully')
            return redirect('list')
    else:
        form = StudentForm()
    context = {'title': 'Create Student','form':form}
    return render(request,'stud/create.html',context)

def details(request, id):
    student = Student.objects.get(pk = id)
    form = StudentForm(request.POST or None, instance=student)
    
    context = {'title': 'Student Details','form':form, 'student':student}
    return render(request,'stud/view.html',context)
    
def edit(request, id):
    if request.method == "POST":
      student = Student.objects.get(pk = id)
      form = StudentForm(request.POST or None, instance=student)
      if form.is_valid():
          form.save()
          messages.success(request,'Data Updated successfully')
          return redirect('list')
    else:
        student = Student.objects.get(pk = id)
        form = StudentForm(request.POST or None, instance=student)
        
    context = {'title': 'Edit Student','form':form}
    return render(request,'stud/create.html',context)    

def delete(request, id):
    
    student = Student.objects.get(pk = id)
    student.delete()
    messages.success(request,'Data deleted successfully')
    return redirect('list')

def register(request):
    
     if request.method == "POST":
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save()
                user.save()
                messages.success(request,'User created successfully')
                return redirect('home')
   
     else:
         form = SignUpForm()       
     context = {'title': 'Register User','form':form}
     return render(request,'registration/register.html',context)

        
    

utils/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib import messages
from .forms import EmailForm
from studentapp.models import Student
import csv
# Create your views here.

def sent_mail(request):
    if request.method == "POST":
        form = EmailForm(request.POST)
        if form.is_valid():
            varsubject = form.cleaned_data['subject']
            varmessage = form.cleaned_data['message']
            varemail = form.cleaned_data['email']
            
            varmail = EmailMessage(varsubject,varmessage,settings.EMAIL_HOST_USER,[varemail])
            
            # attach file here 
            if request.FILES:
                varFiles = request.FILES.getlist('attach')
                for f in varFiles:
                    varmail.attach(f.name,f.read(),f.content_type)
            # end of attach config
            
            varmail.send()
            messages.success(request,'Email Sent Successfully')
            return redirect('/')
    else:
            form = EmailForm()
            # context = {'form':form}    
    return render(request,'email/emailform.html',{'form':form})

def export_csv(request):
    response = HttpResponse(content_type = 'text/csv')
    response['Content-Disposition'] = 'attachment;filename= "student.csv"'
    
    writer = csv.writer(response)
    writer.writerow(['Id', 'Student Name', 'Email Address', 'Birth Date', 'Gender']) 
    students = Student.objects.all().values_list('id', 'name', 'email', 'dob', 'gender')
    
    
    for std in students:
        writer.writerow(std)
    
    return response

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="images/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>   
    {% block stylesheet %}
        
    {% endblock stylesheet %}
        
</head>
<body>
    <div class="container">
        <div>
            <img src="{% static 'images/logo.png' %}" alt="" width="100%">
        </div>
        <div>
            {% include 'navbar.html' %}
        </div>
       <main>
           <div style="min-height:600px;" >
            {% if messages %}
            
                    
                    
                        
                        {% for message in messages %}
                        
                        <script>
                            Swal.fire("{{message}}","Thank you ...!!","{{message.tags}}");
                          </script>

                        {% endfor %}
                            
                    
                        
                
              {% endif %}
                
                {% block content %}
                    
                {% endblock content %}
                    
           </div>
       </main>
       <footer>
         {% include 'footer.html' %}
       </footer>
   </div>
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>  
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script>
        $(function(){
            $("#id_dob").datepicker({
                format:"yyyy-mm-dd", 
                autoclose: true, 
                todayHighlight: true, 
                orientation: "auto", 
                title: "Date of Birth", 
                endDate: "-0d"
            });
        });

        function PrintDiv(divname){
            var presentcontent = document.getElementById(divname).innerHTML;
            var oldcontent = document.body.innerHTML;
            document.body.innerHTML = presentcontent;
            window.print();
            document.body.innerHTML = oldcontent;
        }
    </script>
   {% block javascript %}
       
   {% endblock javascript %}
       

</body>

</html>

templates/footer.html
{% load static %}
<footer class="text-center font-small mt-3 bg-dark text-white ">
    <div>
      &copy;copyright 2021 Dhaka,Bangladesh
      <a href="#" target="_blank">Gulshan Rahman</a>
     </div>

  </footer>

templates/navbar.html
{% load static %}
<div>
    <nav class="navbar navbar-expand-lg navbar-light bg-faded">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/favicon.ico' %}" alt="">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li><li class="nav-item">
                <a class="nav-link" href="{% url 'about'%}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'list'%}">Student List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sendemail'%}">Send Email</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'exportcsv'%}">Export CSV</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Students Info
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Admission</a></li>
                  <li><a class="dropdown-item" href="#">Library</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Alumni</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            
            {% if user.is_authenticated %}
              <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                  <a href="#" class="nav-link">Hi {{ user.username }}</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'logout' %}" class="nav-link">Log out</a>
                </li>
              </ul>
            {% else %}
              <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                  <a href="{% url 'login' %}" class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'register' %}" class="nav-link">Register</a>
                </li>
              </ul>
            {% endif %}
              
          </div>
        </div>
      </nav>
</div>

templates/stud/about.html
{% extends 'base.html' %}
{%load static%}

{%block content%}
<h1>About</h1>
<div class="mapouter">
    <div class="gmap_canvas"><iframe width="1000" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=860%20East%20Shewrapara&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://fmovies-online.net">fmovies</a><br><style>.mapouter{position:relative;text-align:right;height:500px;width:1000px;}</style><a href="https://www.embedgooglemap.net"></a><style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:1000px;}</style>
    </div>
</div>
{%endblock content%}

templates/stud/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}  



<form action="" method="POST">
    <!-- cross reference mendatory -->
    {% csrf_token %}

<div class="row">
    <div class="col-sm-6">
        <div class="card">
           <div class="card-header">
            <h1>{{ title }}</h1>
           </div>
            <div class="card-body">
                {% load crispy_forms_tags %}
                {{ form | crispy }}
                <br>
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
                <a href="{% url 'list' %}" class="btn btn-warning mt-3">Back to list</a>
            </div>
          </div> 

    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
             ...
            </div>
             <div class="card-body">
               
             </div>
           </div> 
    </div>

</div>
</form> 
    
{% endblock content %}
    

templates/stud/home.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<div>
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/image-3.jpg' %}" class="d-block w-100 h-75" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/image-2.jpg' %}" class="d-block w-100 h-75" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/image-3.jpg' %}" class="d-block w-100 h-75" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon " aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon " aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


{% endblock content %}   

templates/stud/list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}      

<div>
  <a href="{% url 'create' %}" class="btn btn-primary">Add New Student</a>
</div>
<br>  
<button class="btn btn-primary" onclick="PrintDiv('report');"> Print Report</button>
   
    <div id="report">

     </div> 
     <br>
        <div>
            <h1>List of All Students</h1>
            <hr>
        </div>
        <div>
            <table class="table table-striped table-hover">
                <thead class="table-dark">
                    <tr>
                        <td>ID</td>
                        <td>Name</td>
                        <td>Email Address</td>
                        <td>Date of Birth</td>
                        <td>Gender</td>
                        {% if user.is_authenticated and user.is_staff %}
                        <td>Actions</td>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    
                    {% for stud in students %}
                    <tr>
                        <td>{{ stud.id }}</td>
                        <td>{{ stud.name }}</td>
                        <td>{{ stud.email }}</td>
                        <td>{{ stud.dob|date:'m-d-Y' }}</td>
                        <td>{{ stud.gender }}</td>
                        <td>
                          <a href="{% url 'view' stud.id %}" class="btn btn-info" title="view"><i class="fa fa-eye fa-2x"></i></a>
                          <a href="{% url 'edit' stud.id %}" class="btn btn-warning" title="edit"><i class="fa fa-edit fa-2x"></i></a>
                         
                          
                           
                          <a href="{% url 'delete' stud.id %}" onclick="return confirm('Are you sure, you want to delete record?');" class="btn btn-danger" title="delete"><i class="fa fa-trash-restore-alt fa-2x"></i></a>
                          
                        </td>
                    </tr>
                        
                    {% endfor %}
                        
                        
                </tbody>
                <tfoot>
                            
                </tfoot>
            </table>
           <hr>

          
           
           
           <!-- Paginigation starts -->
  {% if students.has_other_pages %}
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if students.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ students.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span aria-hidden="true">&laquo;</span>
      </li>
      {% endif %}
  
      {% for i in students.paginator.page_range %}
  
      {% if students.number == i %}
      <li class="page-item active" aria-current="page">
        <a class="page-link" href="#">{{ i }}</a>
      </li>
  
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
  
      <li class="page-item">
        {% if students.has_next %}
  
      <li class="page-item">
        <a class="page-link" href="?page={{students.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
  
      {% else %}
      <li class="page-item disabled">
  
        <span aria-hidden="true">&raquo;</span>
      </li>
      {% endif %}
      </li>
    </ul>
  </nav>
  
  {%endif%}
                
        </div>
        {% endblock content %}
   

templates/stud/view.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <form action="">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                   <div class="card-header">
                    <h1>{{ title }}</h1>
                   </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Student ID:</label>
                            <div class="col-sm-4">
                                {{ student.id }}
                
                            </div>
                          </div>
                
                          <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Student Name:</label>
                            <div class="col-sm-4">
                                {{ student.name }}
                
                            </div>
                          </div>
                
                          <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Email Address:</label>
                            <div class="col-sm-6">
                                {{ student.email }}
                
                            </div>
                          </div>
                
                          <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Date Of Birth:</label>
                            <div class="col-sm-4">
                                {{ student.dob|date:'Y-m-d' }}
                
                            </div>
                          </div>
                
                          <div class="form-group row-cols-4">
                            <label class="col-sm-4 col-form-label">Gender:</label>
                            <div class="col-sm-4">
                                {{ student.gender }}
                
                            </div>
                          </div>

                          <div class="form-group row">
                            <label class="col-sm-4 col-form-label"></label>
                            <div class="col-sm-4">
                               
                
                            </div>
                          </div>
                        <a href="{% url 'list' %}" class="btn btn-warning">Back to list</a>
                    </div>
                  </div> 
        
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-header">
                     ...
                    </div>
                     <div class="card-body">
                       
                     </div>
                   </div> 
            </div>
        
        </div>
       

          
    </form>
    
{% endblock content %}
    